### PR TITLE
feat #60: substrate update

### LINKED ISSUE #60: WSH - Substrate Update

### PR DESCRIPTION
**Pull request by bekolb**
## fixes #60 
Update node and runtime to current substrate node template 1.0.0
Also renames all occurrences of `node-template` to `mashnet-node`

## How to test:
Launch a mashnet and run through every functionality of KILT that involves the blockchain.

## Checklist:

- [x] I have verified that the code works (by running a single node)
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by tjwelde** [comment]
@LeonFLK Please test with following instructions:
- Run a set of nodes (more than 2 / mix of validators and full-nodes)
- Compile the wasm-runtime from this PR and update the chain (via the chain-explorer)
- Natively update the nodes

Observe, what happens and report, if something went wrong.
Thanks

**Comment by LeonFLK** [comment]
Upgrading via https://substrate-ui.parity.io/#/toolbox with the sudo module bricks the chain with the error message:

**Aura authorship task terminated unexpectedly. Restarting**

The Chain stops producing blocks at this point. The new substrate runtime version introduced breaking changes and is not compatible with our Testnet.
I will now test the chain functionality with our demo-client

**Comment by LeonFLK** [comment]
Created new chainspec to share in our network.
Addresses seem to be calculated differently, sudo key and authority and endowed ids changed last 4 characters.
demo client is not able to really call the API/RPC, getting errors like: 
 - RPC-CORE: getMetadata (block: Hash): Metadata:: Object.values(...)[index] is not a constructor
 - API/DECORATOR: loadMeta ExtError: getMetadata (block: Hash): Metadata:: Object.values(...)[index] is not a constructor

**Comment by tjwelde** [comment]
I tested the whole functionality with the demo client and it works very good.

**Comment by tjwelde** [comment]
I think we need to use the new chainspec and restart the chain. We might need to reconfigure our validators on aws.

**Pull request merged**
