### PR TITLE
feat: add support for runtime migration testing

### PR DESCRIPTION
**Pull request by Diiaablo95**
Does not fix any specific issue, but partially covers https://github.com/KILTprotocol/ticket/issues/1396.

## How to test:

Live testing requires a running blockchain/parachain to test the migration against. 

To run the test migration against the mashnet, run:

```
cargo run -p mashnet-node --features try-runtime -- try-runtime --chain <chain_spec> --execution wasm --wasm-execution "interpreted-i-know-what-i-do" live <node_ws_url>
```

To run the test migration against a parachain, run:

```
cargo run -p kilt-parachain --features try-runtime -- try-runtime --chain <chain_spec> --execution wasm --wasm-execution compiled live <node_ws_url>
```

### CODE REVIEW

**Comment by Diiaablo95** [comment]
@weichweich fixed in https://github.com/KILTprotocol/mashnet-node/pull/196/commits/4061f291e8bd34a8119fc122171c49f528ef95ee.

**Comment by weichweich** [comment]
@Diiaablo95 

I tried this on the mashnet and got the following: 

```
❯ cargo run -p mashnet-node --features try-runtime -- try-runtime --chain kilt-testnet --execution wasm --wasm-execution "interpreted-i-know-what-i-do" live wss://full-nodes.kilt.io:9944/
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/mashnet-node try-runtime --chain kilt-testnet --execution wasm --wasm-execution interpreted-i-know-what-i-do live 'wss://full-nodes.kilt.io:9944/'`
2021-06-17 08:48:45 initializing remote client to "wss://full-nodes.kilt.io:9944/"    
2021-06-17 08:48:45 scraping key-pairs from remote @ 0x8def5212698705d76966cc18b34eba80f272590e56039b278a6d90e455b82b9d    
2021-06-17 08:48:45 downloading data for all modules.    
2021-06-17 08:48:50 Querying a total of 8805 keys    
2021-06-17 08:48:53 extending externalities with 1 manually injected keys    
2021-06-17 08:48:53 injecting a total of 8806 keys    
Error: Input("failed to execute 'TryRuntime_on_runtime_upgrade' due to Wasmi(Function(\"Module doesn't have export TryRuntime_on_runtime_upgrade\"))")
```

Am I doing something wrong? 😥

**Comment by weichweich** [comment]
> @Diiaablo95
> 
> I tried this on the mashnet and got the following:
> 
> ```
> ❯ cargo run -p mashnet-node --features try-runtime -- try-runtime --chain kilt-testnet --execution wasm --wasm-execution "interpreted-i-know-what-i-do" live wss://full-nodes.kilt.io:9944/
>     Finished dev [unoptimized + debuginfo] target(s) in 0.33s
>      Running `target/debug/mashnet-node try-runtime --chain kilt-testnet --execution wasm --wasm-execution interpreted-i-know-what-i-do live 'wss://full-nodes.kilt.io:9944/'`
> 2021-06-17 08:48:45 initializing remote client to "wss://full-nodes.kilt.io:9944/"    
> 2021-06-17 08:48:45 scraping key-pairs from remote @ 0x8def5212698705d76966cc18b34eba80f272590e56039b278a6d90e455b82b9d    
> 2021-06-17 08:48:45 downloading data for all modules.    
> 2021-06-17 08:48:50 Querying a total of 8805 keys    
> 2021-06-17 08:48:53 extending externalities with 1 manually injected keys    
> 2021-06-17 08:48:53 injecting a total of 8806 keys    
> Error: Input("failed to execute 'TryRuntime_on_runtime_upgrade' due to Wasmi(Function(\"Module doesn't have export TryRuntime_on_runtime_upgrade\"))")
> ```
> 
> Am I doing something wrong? 😥

removing the `--chain` option solved that. Thanks @Diiaablo95

**Review by weichweich — APPROVED** [review]
LGTM!

**Review by wischli — APPROVED** [review]
LGTM!

**Pull request merged**
