### PR TITLE
feat: simple fee adjustment

### PR DESCRIPTION
**Pull request by weichweich**
## Checklist:

- [ ] I have verified that the code works
  - [ ] No panics! (checked arithmetic ops, no indexing `array[3]` use `get(3)`, ...)
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] This PR does not introduce new custom types
  - [ ] If not, I have opened a companion PR with the type changes in the [KILT types-definitions repository](https://github.com/KILTprotocol/type-definitions/pulls)
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by wischli** [comment]
TODO: Add `RocksDbWeight` to `DbWeight` config parameter.

**Comment by weichweich** [comment]
Is says `Fees of 9.8600 milli KILT will be applied to the submission`

**Review by wischli — CHANGES_REQUESTED** [review]
Please also add `type DbWeight = RocksDbWeight;` for the `parachain` runtime.

**Review by wischli — APPROVED** [review]
LGTM! May the merge train continue 🚂

**Pull request merged**
