### PR TITLE
ci: add separate cargo test

### PR DESCRIPTION
**Pull request by wischli**
## No ticket

In #231 none of the CI tests failed but `cargo test` was broken for the did pallet. This should be fixed by #235. However, in #235 we stumbled into the same error. Thus, I think we should add a separate `cargo test step to the CI as proposed here.

## Checklist:

- [x] I have verified that the code works
  - [x] No panics! (checked arithmetic ops, no indexing `array[3]` use `get(3)`, ...)
- [x] I have verified that the code is easy to understand
- [x] This PR does not introduce new custom types
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [x] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by wischli** [comment]
CI failure proofs my point of adding this to the CI. They should be fixed after merging #235 as mentioned above.

**Comment by Diiaablo95** [comment]
Should we add `--all-targets` also to `cargo test`? I guess we could go for `cargo test --all --all-targets` and `cargo test --all --all-features --all-targets`?

**Comment by wischli** [comment]
> Should we add `--all-targets` also to `cargo test`? I guess we could go for `cargo test --all --all-targets` and `cargo test --all --all-features --all-targets`?

Yeah, that sounds good.

**Review by weichweich — APPROVED** [review]
my only objection is that this will increase the load on the server. We have 2 concurrent jobs at the moment. Maybe we should increase that to 3 or 4. 🤔

**Pull request merged**
