### PR TITLE
feat: use sr25519 for dev accounts

### PR DESCRIPTION
**Pull request by weichweich**
## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Review by wischli — APPROVED** [review]
LGTM

**Review by Diiaablo95 — APPROVED** [review]

**Comment by rflechtner** [comment]
pls have both ed225519 & sr25519 dev accounts so don't have to change the sdk rn

**Comment by weichweich** [comment]
> pls have both ed225519 & sr25519 dev accounts so don't have to change the sdk rn

@rflechtner The root account is a `sr25519` account. Root calls are not used in the SDK right?

**Comment by rflechtner** [comment]
> > pls have both ed225519 & sr25519 dev accounts so don't have to change the sdk rn
> 
> @rflechtner The root account is a `sr25519` account. Root calls are not used in the SDK right?

No, we don't do that rn

**Review by rflechtner — APPROVED** [review]
LGTM

**Pull request merged**
