### PR TITLE
chore: remove crowdloan pallet

### PR DESCRIPTION
**Pull request by weichweich**
## No Ticket

- remove and clean the Crowdloan Contributor pallet (it served it's purpose)
- pay the dust to the treasury

## Checklist:

- [ ] I have verified that the code works
  - [ ] No panics! (checked arithmetic ops, no indexing `array[3]` use `get(3)`, ...)
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] This PR does not introduce new custom types
  - [ ] If not, I have opened a companion PR with the type changes in the [KILT types-definitions repository](https://github.com/KILTprotocol/type-definitions/pulls)
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Review by Diiaablo95 — APPROVED** [review]
LGTM! I am just unsure whether it is best to change the pallet and runtime versions inside a PR like this. I would rather change them at the beginning or end of the development cycle with a separate PR.

**Comment by weichweich** [comment]
> LGTM! I am just unsure whether it is best to change the pallet and runtime versions inside a PR like this. I would rather change them at the beginning or end of the development cycle with a separate PR.

yes. i reverted the version upgrade

**Comment by Diiaablo95** [comment]
I also updated the PR description 👌

**Review by wischli — APPROVED** [review]
LGTM

**Pull request merged**
