### PR TITLE
chore: Updates toolchain version

### PR DESCRIPTION
**Pull request by ggera**
## NO TICKET
updated the toolchain init script so that the benchbot and ci can call it

### CODE REVIEW

**Review by ntn-x2 — COMMENTED** [review]
Do we also need to fix the CI Docker images that we use? I made some tests this morning and it was using the old toolchain.

**Comment by ggera** [comment]
> Do we also need to fix the CI Docker images that we use? I made some tests this morning and it was using the old toolchain.

The ci seems to override the docker image toolchain by picking settings in the toolchain file

**Review by ntn-x2 — APPROVED** [review]
All good then 👍

**Comment by ntn-x2** [comment]
I just saw that our release pipeline uses srtool v1.57, when we should probably use v1.59 as our toolchain specifies @ggera

**Comment by ggera** [comment]
> 

That is correct, the [srtool rust version seems hard coded ](https://hub.docker.com/layers/srtool/paritytech/srtool/1.57.0/images/sha256-912c690ddf167a4b897a16d120c0af70159b873102184289d135434ecead5bdd?context=explore) and not sure if it overridable.

**Pull request merged**
